name: Deploy static content to Pages

env:
  PUBLISH_DIR: ElliotPurdum.com/bin/Release/net10.0/publish/wwwroot

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Get latest .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Build Source Project
        run: |
          cd ElliotPurdum.com.Source
          dotnet build -c Release

      - name: Generate Static Pages
        run: |
          cd BlogGenerator/TimPurdum.Dev.BlogGenerator.Compiler
          dotnet run -c Release

      - name: Publish app
        run: |
          cd ElliotPurdum.com
          dotnet publish -c Release

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.PUBLISH_DIR }}

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
